### ISSUE TITLE
CSS only for visual changes without hover

### ISSUE THREAD

**Issue by h4wwk3ye** [drannex42/vivaldi-mods#5]
Hey can you please provide the CSS part that's only required for making it look like edge and not the hover to expand part. I am trying to remove some CSS, but can't get the same visual look as I only use pinned vertical tabs in Edge.

**Comment by macleod-ee** [comment]
I'm sure it's possible, but I no longer use Vivaldi. I now use Firefox and maintain the FirefoxSidebar theme and settings. I don't believe I will be able to help, sorry!
